### ISSUE TITLE
Sample failing with KeyError: None

### ISSUE THREAD

**Issue by JezSw** [iqbal-lab-org/viridian_workflow#47] opened 2022-03-03 15:24 UTC
When running the following command and files we get ther full error log below.

```
viridian_workflow run_one_sample             --tech illumina             --ref_fasta ref.fa             --reads1 241c0636-45e2-4ec3-82d4-ab58c9992d66_1.fastq.gz             --reads2 241c0636-45e2-4ec3-82d4-ab58c9992d66_2.fastq.gz             --outdir 241c0636-45e2-4ec3-82d4-ab58c9992d66_outdir/             --sample_name 241c0636-45e2-4ec3-82d4-ab58c9992d66             --keep_bam

[2022-03-03T10:35:50 viridian_workflow INFO] Start running viridian_workflow, output dir: 241c0636-45e2-4ec3-82d4-ab58c9992d66_outdir/
[2022-03-03T10:35:50 viridian_workflow INFO] No primer schemes provided. Using all built in schemes
[2022-03-03T10:35:50 viridian_workflow INFO] Processed amplicon scheme files. Amplicon scheme names: COVID-AMPLISEQ-V1,COVID-ARTIC-V3,COVID-ARTIC-V4,COVID-MIDNIGHT-1200
[2022-03-03T10:35:50 viridian_workflow INFO] Mapping reads to reference
[M::mm_idx_gen::0.010*0.89] collected minimizers
[M::mm_idx_gen::0.012*0.91] sorted minimizers
[M::main::0.012*0.91] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.012*0.90] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.013*0.91] distinct minimizers: 4989 (99.98% are singletons); average occurrences: 1.002; average spacing: 5.979; total length: 29903
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -R @RG\tID:1\tSM:241c0636-45e2-4ec3-82d4-ab58c9992d66 -t 1 -a -x sr ref.fa 241c0636-45e2-4ec3-82d4-ab58c9992d66_1.fastq.gz 241c0636-45e2-4ec3-82d4-ab58c9992d66_2.fastq.gz
[M::main] Real time: 0.020 sec; CPU: 0.013 sec; Peak RSS: 0.004 GB
[2022-03-03T10:35:50 viridian_workflow INFO] Detecting amplicon scheme and gathering read statistics
Traceback (most recent call last):
  File "/usr/local/bin/viridian_workflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/__main__.py", line 215, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/tasks/run_one_sample.py", line 13, in run
    one_sample_pipeline.run_one_sample(
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/one_sample_pipeline.py", line 447, in run_one_sample
    pipeline.run()
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/one_sample_pipeline.py", line 418, in run
    self.initial_read_map_and_detect_amplicon_scheme()
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/one_sample_pipeline.py", line 191, in initial_read_map_and_detect_amplicon_scheme
    self.amplicon_tsv = self.amplicon_scheme_name_to_tsv[chosen_scheme]
KeyError: None
```
 This seems to be caused by the line 
```
minimap2 -R @RG\tID:1\tSM:241c0636-45e2-4ec3-82d4-ab58c9992d66 -t 1 -a -x sr ref.fa 241c0636-45e2-4ec3-82d4-ab58c9992d66_1.fastq.gz 241c0636-45e2-4ec3-82d4-ab58c9992d66_2.fastq.gz
```
causing the error
```
[ERROR] no ID within the read group line
```

[241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz](https://github.com/iqbal-lab-org/viridian_workflow/files/8178916/241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz)
[241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz](https://github.com/iqbal-lab-org/viridian_workflow/files/8178917/241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz)

**Comment by JezSw** [comment] 2022-03-03 15:27
This is with v0.3.6

**Comment by martinghunt** [comment] 2022-03-03 15:55
I can't reproduce this. Have tried using the v0.3.6 container from the releases page. Also downloaded the tarball of the code and also can't reproduce. In both cases, it runs to completion with no errors.

Using code tarball:
```
wget https://github.com/iqbal-lab-org/viridian_workflow/archive/refs/tags/v0.3.6.tar.gz                                                                                                                                                        

tar xf v0.3.6.tar.gz

PYTHONPATH=$PWD/viridian_workflow-0.3.6 python3 -m viridian_workflow run_one_sample --force --debug --tech illumina --ref_fasta viridian_workflow-0.3.6/viridian_workflow/amplicon_scheme_data/MN908947.fasta --reads1 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz --reads2 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz --outdir OUT --sample_name 241c0636-45e2-4ec3-82d4-ab58c9992d66 --keep_bam
[2022-03-03T15:49:57 viridian_workflow INFO] --force option used, so deleting OUT if it exists
[2022-03-03T15:49:57 viridian_workflow INFO] Start running viridian_workflow, output dir: OUT
[2022-03-03T15:49:57 viridian_workflow INFO] No primer schemes provided. Using all built in schemes
[2022-03-03T15:49:57 viridian_workflow INFO] Processed amplicon scheme files. Amplicon scheme names: COVID-AMPLISEQ-V1,COVID-ARTIC-V3,COVID-ARTIC-V4,COVID-MIDNIGHT-1200
[2022-03-03T15:49:57 viridian_workflow INFO] Mapping reads to reference
[M::mm_idx_gen::0.001*1.34] collected minimizers
[M::mm_idx_gen::0.002*1.21] sorted minimizers
[M::main::0.002*1.21] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*1.21] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*1.19] distinct minimizers: 4989 (99.98% are singletons); average occurrences: 1.002; average spacing: 5.979
[M::worker_pipeline::1.500*1.00] mapped 98000 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -R @RG\tID:1\tSM:241c0636-45e2-4ec3-82d4-ab58c9992d66 -t 1 -a -x sr viridian_workflow-0.3.6/viridian_workflow/amplicon_scheme_data/MN908947.fasta 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz
[M::main] Real time: 1.508 sec; CPU: 1.508 sec; Peak RSS: 0.103 GB
[2022-03-03T15:49:59 viridian_workflow INFO] Detecting amplicon scheme and gathering read statistics
[2022-03-03T15:50:03 viridian_workflow INFO] Processing files for chosen amplicon scheme COVID-ARTIC-V3
.... etc...
```

Using singularity image:

```
wget https://github.com/iqbal-lab-org/viridian_workflow/releases/download/v0.3.6/viridian_workflow_v0.3.6.img

singularity exec viridian_workflow_v0.3.6.img viridian_workflow run_one_sample --force --debug --tech illumina --ref_fasta viridian_workflow-0.3.6/viridian_workflow/amplicon_scheme_data/MN908947.fasta --reads1 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz --reads2 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz --outdir OUT2 --sample_name 241c0636-45e2-4ec3-82d4-ab58c9992d66 --keep_bam
[2022-03-03T15:54:16 viridian_workflow INFO] --force option used, so deleting OUT2 if it exists
[2022-03-03T15:54:16 viridian_workflow INFO] Start running viridian_workflow, output dir: OUT2
[2022-03-03T15:54:16 viridian_workflow INFO] No primer schemes provided. Using all built in schemes
[2022-03-03T15:54:16 viridian_workflow INFO] Processed amplicon scheme files. Amplicon scheme names: COVID-AMPLISEQ-V1,COVID-ARTIC-V3,COVID-ARTIC-V4,COVID-MIDNIGHT-1200
[2022-03-03T15:54:16 viridian_workflow INFO] Mapping reads to reference
[M::mm_idx_gen::0.003*1.56] collected minimizers
[M::mm_idx_gen::0.004*1.42] sorted minimizers
[M::main::0.004*1.42] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.004*1.42] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.004*1.40] distinct minimizers: 4989 (99.98% are singletons); average occurrences: 1.002; average spacing: 5.979; total length: 29903
[M::worker_pipeline::1.562*1.00] mapped 98000 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -R @RG\tID:1\tSM:241c0636-45e2-4ec3-82d4-ab58c9992d66 -t 1 -a -x sr viridian_workflow-0.3.6/viridian_workflow/amplicon_scheme_data/MN908947.fasta 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_1.fastq.gz 241c0636-45e2-4ec3-82d4-ab58c9992d66.reads_2.fastq.gz
[M::main] Real time: 1.569 sec; CPU: 1.571 sec; Peak RSS: 0.102 GB
[2022-03-03T15:54:18 viridian_workflow INFO] Detecting amplicon scheme and gathering read statistics
[2022-03-03T15:54:22 viridian_workflow INFO] Processing files for chosen amplicon scheme COVID-ARTIC-V3
... etc ...
```

**Comment by martinghunt** [comment] 2022-03-03 16:03
I have managed to reproduce this by inputting two empty FASTQ files.

**Comment by JezSw** [comment] 2022-03-03 16:15
You're right. Hmmmmmm I'm wondering if there's something else going on in our system. Being able to replicate with a blank file seems to indicate that could be the root issue.

**Comment by martinghunt** [comment] 2022-03-03 16:26
A bit more digging if it helps: the minimap2 error
```
[ERROR] no ID within the read group line
```
is a red herring. The minimap2 command in stdout/err from viridian workflow is made by minimap2. The actual call that is made by the python code has single quotes around the `-R` option, like this:
```
minimap2 -R '@RG\\tID:1\\tSM:241c0636-45e2-4ec3-82d4-ab58c9992d66' ...
```
Those quotes stop that minimap2 error. minimap2 must be removing the quotes when it prints the command.

**Comment by iqbal-lab** [comment] 2022-07-20 13:18
closing this. will raise an issue that we should cope gracefully with 2 empty fastq

**Closed by iqbal-lab** 2022-07-20 13:18 UTC
